// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

/// The account type of the user.
public enum AccountType: String, Codable, CaseIterable {
    case atlassian
    case app
    case customer
    case unknown
}
