// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

/// The type of ancestor.
public enum AncestorType: String, Codable, CaseIterable {
    case page
    case whiteboard
    case database
    case embed
    case folder
}
