// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct AttachmentLinks: Codable {
    /// Web UI link of the content.
    public var webui: String?
    /// Download link of the content.
    public var download: String?

    public init(webui: String? = nil, download: String? = nil) {
        self.webui = webui
        self.download = download
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.webui = try values.decodeIfPresent(String.self, forKey: "webui")
        self.download = try values.decodeIfPresent(String.self, forKey: "download")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(webui, forKey: "webui")
        try values.encodeIfPresent(download, forKey: "download")
    }
}
