// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct ChildCustomContent: Codable {
    /// ID of the child custom content.
    public var id: String?
    /// The status of the content.
    public var status: OnlyArchivedAndCurrentContentStatus?
    /// Title of the custom content.
    public var title: String?
    /// Custom content type.
    public var type: String?
    /// ID of the space the custom content is in.
    public var spaceID: String?

    public init(id: String? = nil, status: OnlyArchivedAndCurrentContentStatus? = nil, title: String? = nil, type: String? = nil, spaceID: String? = nil) {
        self.id = id
        self.status = status
        self.title = title
        self.type = type
        self.spaceID = spaceID
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.id = try values.decodeIfPresent(String.self, forKey: "id")
        self.status = try values.decodeIfPresent(OnlyArchivedAndCurrentContentStatus.self, forKey: "status")
        self.title = try values.decodeIfPresent(String.self, forKey: "title")
        self.type = try values.decodeIfPresent(String.self, forKey: "type")
        self.spaceID = try values.decodeIfPresent(String.self, forKey: "spaceId")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(id, forKey: "id")
        try values.encodeIfPresent(status, forKey: "status")
        try values.encodeIfPresent(title, forKey: "title")
        try values.encodeIfPresent(type, forKey: "type")
        try values.encodeIfPresent(spaceID, forKey: "spaceId")
    }
}
