// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct ChildPage: Codable {
    /// ID of the page.
    public var id: String?
    /// The status of the content.
    public var status: OnlyArchivedAndCurrentContentStatus?
    /// Title of the page.
    public var title: String?
    /// ID of the space the page is in.
    public var spaceID: String?
    /// Position of child page within the given parent page tree.
    public var childPosition: Int32?

    public init(id: String? = nil, status: OnlyArchivedAndCurrentContentStatus? = nil, title: String? = nil, spaceID: String? = nil, childPosition: Int32? = nil) {
        self.id = id
        self.status = status
        self.title = title
        self.spaceID = spaceID
        self.childPosition = childPosition
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.id = try values.decodeIfPresent(String.self, forKey: "id")
        self.status = try values.decodeIfPresent(OnlyArchivedAndCurrentContentStatus.self, forKey: "status")
        self.title = try values.decodeIfPresent(String.self, forKey: "title")
        self.spaceID = try values.decodeIfPresent(String.self, forKey: "spaceId")
        self.childPosition = try values.decodeIfPresent(Int32.self, forKey: "childPosition")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(id, forKey: "id")
        try values.encodeIfPresent(status, forKey: "status")
        try values.encodeIfPresent(title, forKey: "title")
        try values.encodeIfPresent(spaceID, forKey: "spaceId")
        try values.encodeIfPresent(childPosition, forKey: "childPosition")
    }
}
