// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public enum ClassificationLevelColor: String, Codable, CaseIterable {
    case red = "RED"
    case redBold = "RED_BOLD"
    case orange = "ORANGE"
    case yellow = "YELLOW"
    case green = "GREEN"
    case blue = "BLUE"
    case navy = "NAVY"
    case teal = "TEAL"
    case purple = "PURPLE"
    case grey = "GREY"
    case lime = "LIME"
}
