// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

/// Body of the custom content. Only one body format should be specified as the property
/// for this object, e.g. `storage`.
public struct CustomContentNestedBodyWrite: Codable {
    public var storage: CustomContentBodyWrite?
    public var atlasDocFormat: CustomContentBodyWrite?
    public var raw: CustomContentBodyWrite?

    public init(storage: CustomContentBodyWrite? = nil, atlasDocFormat: CustomContentBodyWrite? = nil, raw: CustomContentBodyWrite? = nil) {
        self.storage = storage
        self.atlasDocFormat = atlasDocFormat
        self.raw = raw
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.storage = try values.decodeIfPresent(CustomContentBodyWrite.self, forKey: "storage")
        self.atlasDocFormat = try values.decodeIfPresent(CustomContentBodyWrite.self, forKey: "atlas_doc_format")
        self.raw = try values.decodeIfPresent(CustomContentBodyWrite.self, forKey: "raw")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(storage, forKey: "storage")
        try values.encodeIfPresent(atlasDocFormat, forKey: "atlas_doc_format")
        try values.encodeIfPresent(raw, forKey: "raw")
    }
}
