// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct FooterCommentModel: Codable {
    /// ID of the comment.
    public var id: String?
    /// The status of the content.
    public var status: ContentStatus?
    /// Title of the comment.
    public var title: String?
    /// ID of the blog post containing the comment if the comment is on a blog post.
    public var blogPostID: String?
    /// ID of the page containing the comment if the comment is on a page.
    public var pageID: String?
    /// ID of the attachment containing the comment if the comment is on an attachment.
    public var attachmentID: String?
    /// ID of the custom content containing the comment if the comment is on a custom content.
    public var customContentID: String?
    /// ID of the parent comment if the comment is a reply.
    public var parentCommentID: String?
    public var version: Version?
    public var properties: Properties?
    public var operations: Operations?
    public var likes: Likes?
    public var versions: Versions?
    /// Contains fields for each representation type requested.
    public var body: BodySingle?
    public var links: CommentLinks?

    public struct Properties: Codable {
        public var results: [ContentProperty]?
        public var meta: OptionalFieldMeta?
        public var links: OptionalFieldLinks?

        public init(results: [ContentProperty]? = nil, meta: OptionalFieldMeta? = nil, links: OptionalFieldLinks? = nil) {
            self.results = results
            self.meta = meta
            self.links = links
        }

        public init(from decoder: Decoder) throws {
            let values = try decoder.container(keyedBy: StringCodingKey.self)
            self.results = try values.decodeIfPresent([ContentProperty].self, forKey: "results")
            self.meta = try values.decodeIfPresent(OptionalFieldMeta.self, forKey: "meta")
            self.links = try values.decodeIfPresent(OptionalFieldLinks.self, forKey: "_links")
        }

        public func encode(to encoder: Encoder) throws {
            var values = encoder.container(keyedBy: StringCodingKey.self)
            try values.encodeIfPresent(results, forKey: "results")
            try values.encodeIfPresent(meta, forKey: "meta")
            try values.encodeIfPresent(links, forKey: "_links")
        }
    }

    public struct Operations: Codable {
        public var results: [Operation]?
        public var meta: OptionalFieldMeta?
        public var links: OptionalFieldLinks?

        public init(results: [Operation]? = nil, meta: OptionalFieldMeta? = nil, links: OptionalFieldLinks? = nil) {
            self.results = results
            self.meta = meta
            self.links = links
        }

        public init(from decoder: Decoder) throws {
            let values = try decoder.container(keyedBy: StringCodingKey.self)
            self.results = try values.decodeIfPresent([Operation].self, forKey: "results")
            self.meta = try values.decodeIfPresent(OptionalFieldMeta.self, forKey: "meta")
            self.links = try values.decodeIfPresent(OptionalFieldLinks.self, forKey: "_links")
        }

        public func encode(to encoder: Encoder) throws {
            var values = encoder.container(keyedBy: StringCodingKey.self)
            try values.encodeIfPresent(results, forKey: "results")
            try values.encodeIfPresent(meta, forKey: "meta")
            try values.encodeIfPresent(links, forKey: "_links")
        }
    }

    public struct Likes: Codable {
        public var results: [Like]?
        public var meta: OptionalFieldMeta?
        public var links: OptionalFieldLinks?

        public init(results: [Like]? = nil, meta: OptionalFieldMeta? = nil, links: OptionalFieldLinks? = nil) {
            self.results = results
            self.meta = meta
            self.links = links
        }

        public init(from decoder: Decoder) throws {
            let values = try decoder.container(keyedBy: StringCodingKey.self)
            self.results = try values.decodeIfPresent([Like].self, forKey: "results")
            self.meta = try values.decodeIfPresent(OptionalFieldMeta.self, forKey: "meta")
            self.links = try values.decodeIfPresent(OptionalFieldLinks.self, forKey: "_links")
        }

        public func encode(to encoder: Encoder) throws {
            var values = encoder.container(keyedBy: StringCodingKey.self)
            try values.encodeIfPresent(results, forKey: "results")
            try values.encodeIfPresent(meta, forKey: "meta")
            try values.encodeIfPresent(links, forKey: "_links")
        }
    }

    public struct Versions: Codable {
        public var results: [Version]?
        public var meta: OptionalFieldMeta?
        public var links: OptionalFieldLinks?

        public init(results: [Version]? = nil, meta: OptionalFieldMeta? = nil, links: OptionalFieldLinks? = nil) {
            self.results = results
            self.meta = meta
            self.links = links
        }

        public init(from decoder: Decoder) throws {
            let values = try decoder.container(keyedBy: StringCodingKey.self)
            self.results = try values.decodeIfPresent([Version].self, forKey: "results")
            self.meta = try values.decodeIfPresent(OptionalFieldMeta.self, forKey: "meta")
            self.links = try values.decodeIfPresent(OptionalFieldLinks.self, forKey: "_links")
        }

        public func encode(to encoder: Encoder) throws {
            var values = encoder.container(keyedBy: StringCodingKey.self)
            try values.encodeIfPresent(results, forKey: "results")
            try values.encodeIfPresent(meta, forKey: "meta")
            try values.encodeIfPresent(links, forKey: "_links")
        }
    }

    public init(id: String? = nil, status: ContentStatus? = nil, title: String? = nil, blogPostID: String? = nil, pageID: String? = nil, attachmentID: String? = nil, customContentID: String? = nil, parentCommentID: String? = nil, version: Version? = nil, properties: Properties? = nil, operations: Operations? = nil, likes: Likes? = nil, versions: Versions? = nil, body: BodySingle? = nil, links: CommentLinks? = nil) {
        self.id = id
        self.status = status
        self.title = title
        self.blogPostID = blogPostID
        self.pageID = pageID
        self.attachmentID = attachmentID
        self.customContentID = customContentID
        self.parentCommentID = parentCommentID
        self.version = version
        self.properties = properties
        self.operations = operations
        self.likes = likes
        self.versions = versions
        self.body = body
        self.links = links
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.id = try values.decodeIfPresent(String.self, forKey: "id")
        self.status = try values.decodeIfPresent(ContentStatus.self, forKey: "status")
        self.title = try values.decodeIfPresent(String.self, forKey: "title")
        self.blogPostID = try values.decodeIfPresent(String.self, forKey: "blogPostId")
        self.pageID = try values.decodeIfPresent(String.self, forKey: "pageId")
        self.attachmentID = try values.decodeIfPresent(String.self, forKey: "attachmentId")
        self.customContentID = try values.decodeIfPresent(String.self, forKey: "customContentId")
        self.parentCommentID = try values.decodeIfPresent(String.self, forKey: "parentCommentId")
        self.version = try values.decodeIfPresent(Version.self, forKey: "version")
        self.properties = try values.decodeIfPresent(Properties.self, forKey: "properties")
        self.operations = try values.decodeIfPresent(Operations.self, forKey: "operations")
        self.likes = try values.decodeIfPresent(Likes.self, forKey: "likes")
        self.versions = try values.decodeIfPresent(Versions.self, forKey: "versions")
        self.body = try values.decodeIfPresent(BodySingle.self, forKey: "body")
        self.links = try values.decodeIfPresent(CommentLinks.self, forKey: "_links")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(id, forKey: "id")
        try values.encodeIfPresent(status, forKey: "status")
        try values.encodeIfPresent(title, forKey: "title")
        try values.encodeIfPresent(blogPostID, forKey: "blogPostId")
        try values.encodeIfPresent(pageID, forKey: "pageId")
        try values.encodeIfPresent(attachmentID, forKey: "attachmentId")
        try values.encodeIfPresent(customContentID, forKey: "customContentId")
        try values.encodeIfPresent(parentCommentID, forKey: "parentCommentId")
        try values.encodeIfPresent(version, forKey: "version")
        try values.encodeIfPresent(properties, forKey: "properties")
        try values.encodeIfPresent(operations, forKey: "operations")
        try values.encodeIfPresent(likes, forKey: "likes")
        try values.encodeIfPresent(versions, forKey: "versions")
        try values.encodeIfPresent(body, forKey: "body")
        try values.encodeIfPresent(links, forKey: "_links")
    }
}
