// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct InlineCommentProperties: Codable {
    /// Property value used to reference the highlighted element in DOM.
    public var inlineMarkerRef: String?
    /// Text that is highlighted.
    public var inlineOriginalSelection: String?

    public init(inlineMarkerRef: String? = nil, inlineOriginalSelection: String? = nil) {
        self.inlineMarkerRef = inlineMarkerRef
        self.inlineOriginalSelection = inlineOriginalSelection
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.inlineMarkerRef = try values.decodeIfPresent(String.self, forKey: "inlineMarkerRef")
        self.inlineOriginalSelection = try values.decodeIfPresent(String.self, forKey: "inlineOriginalSelection")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(inlineMarkerRef, forKey: "inlineMarkerRef")
        try values.encodeIfPresent(inlineOriginalSelection, forKey: "inlineOriginalSelection")
    }
}
