// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

/// Inline comment resolution status
public enum InlineCommentResolutionStatus: String, Codable, CaseIterable {
    case `open`
    case reopened
    case resolved
    case dangling
}
