// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

/// The sort fields for labels. The default sort direction is ascending. To sort in descending order, append a `-` character before the sort field. For example, `fieldName` or `-fieldName`.
public enum LabelSortOrder: String, Codable, CaseIterable {
    case createdDate = "created-date"
    case minuscreatedDate = "-created-date"
    case id
    case minusid = "-id"
    case name
    case minusname = "-name"
}
