// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct Operation: Codable {
    /// The type of operation.
    public var operation: String?
    /// The type of entity the operation type targets.
    public var targetType: String?

    public init(operation: String? = nil, targetType: String? = nil) {
        self.operation = operation
        self.targetType = targetType
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.operation = try values.decodeIfPresent(String.self, forKey: "operation")
        self.targetType = try values.decodeIfPresent(String.self, forKey: "targetType")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(operation, forKey: "operation")
        try values.encodeIfPresent(targetType, forKey: "targetType")
    }
}
