// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct OptionalFieldLinks: Codable {
    /// A relative URL that can be used to fetch results beyond what this include parameter retrieves.
    public var this: String?

    public init(this: String? = nil) {
        self.this = this
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.this = try values.decodeIfPresent(String.self, forKey: "self")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(this, forKey: "self")
    }
}
