// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

/// Body of the page. Only one body format should be specified as the property
/// for this object, e.g. `storage`.
public struct PageNestedBodyWrite: Codable {
    public var storage: PageBodyWrite?
    public var atlasDocFormat: PageBodyWrite?
    public var wiki: PageBodyWrite?

    public init(storage: PageBodyWrite? = nil, atlasDocFormat: PageBodyWrite? = nil, wiki: PageBodyWrite? = nil) {
        self.storage = storage
        self.atlasDocFormat = atlasDocFormat
        self.wiki = wiki
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.storage = try values.decodeIfPresent(PageBodyWrite.self, forKey: "storage")
        self.atlasDocFormat = try values.decodeIfPresent(PageBodyWrite.self, forKey: "atlas_doc_format")
        self.wiki = try values.decodeIfPresent(PageBodyWrite.self, forKey: "wiki")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(storage, forKey: "storage")
        try values.encodeIfPresent(atlasDocFormat, forKey: "atlas_doc_format")
        try values.encodeIfPresent(wiki, forKey: "wiki")
    }
}
