// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

/// Content type of the parent, or null if there is no parent.
public enum ParentContentType: String, Codable, CaseIterable {
    case page
    case whiteboard
    case database
    case embed
    case folder
}
