// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

/// The primary formats a body can be represented as. A subset of BodyRepresentation. These formats are the only allowed formats in certain use cases.
public enum PrimaryBodyRepresentationSingle: String, Codable, CaseIterable {
    case storage
    case atlasDocFormat = "atlas_doc_format"
    case view
    case exportView = "export_view"
    case anonymousExportView = "anonymous_export_view"
    case styledView = "styled_view"
    case editor
}
