// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

/// The principal of the role assignment.
public struct Principal: Codable {
    /// The principal type.
    public var principalType: PrincipalType?
    /// The principal ID.
    public var principalID: String?

    public init(principalType: PrincipalType? = nil, principalID: String? = nil) {
        self.principalType = principalType
        self.principalID = principalID
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.principalType = try values.decodeIfPresent(PrincipalType.self, forKey: "principalType")
        self.principalID = try values.decodeIfPresent(String.self, forKey: "principalId")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(principalType, forKey: "principalType")
        try values.encodeIfPresent(principalID, forKey: "principalId")
    }
}
