// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

/// The principal type.
public enum PrincipalType: String, Codable, CaseIterable {
    case user = "USER"
    case group = "GROUP"
    case accessClass = "ACCESS_CLASS"
}
