// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

/// The role type.
public enum RoleType: String, Codable, CaseIterable {
    case system = "SYSTEM"
    case custom = "CUSTOM"
}
