// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

/// The sort fields for spaces. The default sort direction is ascending. To sort in descending order, append a `-` character before the sort field. For example, `fieldName` or `-fieldName`.
public enum SpaceSortOrder: String, Codable, CaseIterable {
    case id
    case minusid = "-id"
    case key
    case minuskey = "-key"
    case name
    case minusname = "-name"
}
