// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct SpacePermission: Codable {
    /// The identifier for the space permission.
    public var id: String?
    /// The display name for the space permission.
    public var displayName: String?
    /// Describes the space permission’s usage.
    public var description: String?
    /// The permissions required for this permission to be enabled.
    public var requiredPermissionIDs: [String]?

    public init(id: String? = nil, displayName: String? = nil, description: String? = nil, requiredPermissionIDs: [String]? = nil) {
        self.id = id
        self.displayName = displayName
        self.description = description
        self.requiredPermissionIDs = requiredPermissionIDs
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.id = try values.decodeIfPresent(String.self, forKey: "id")
        self.displayName = try values.decodeIfPresent(String.self, forKey: "displayName")
        self.description = try values.decodeIfPresent(String.self, forKey: "description")
        self.requiredPermissionIDs = try values.decodeIfPresent([String].self, forKey: "requiredPermissionIds")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(id, forKey: "id")
        try values.encodeIfPresent(displayName, forKey: "displayName")
        try values.encodeIfPresent(description, forKey: "description")
        try values.encodeIfPresent(requiredPermissionIDs, forKey: "requiredPermissionIds")
    }
}
