// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

/// Contains fields for each representation type requested.
public struct SpaceDescription: Codable {
    public var plain: BodyType?
    public var view: BodyType?

    public init(plain: BodyType? = nil, view: BodyType? = nil) {
        self.plain = plain
        self.view = view
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.plain = try values.decodeIfPresent(BodyType.self, forKey: "plain")
        self.view = try values.decodeIfPresent(BodyType.self, forKey: "view")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(plain, forKey: "plain")
        try values.encodeIfPresent(view, forKey: "view")
    }
}
