// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

/// The formats a space description can be represented as. A subset of BodyRepresentation.
public enum SpaceDescriptionBodyRepresentation: String, Codable, CaseIterable {
    case plain
    case view
}
