// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

/// The icon of the space
public struct SpaceIcon: Codable {
    /// The path (relative to base URL) at which the space's icon can be retrieved. The format should be like `/wiki/download/...` or `/wiki/aa-avatar/...`
    public var path: String?
    /// The path (relative to base URL) that can be used to retrieve a link to download the space icon. 3LO apps should use this link instead of the value provided
    /// in the `path` property to retrieve the icon.
    /// 
    /// Currently this field is only returned for `global` spaces and not `personal` spaces.
    public var apiDownloadLink: String?

    public init(path: String? = nil, apiDownloadLink: String? = nil) {
        self.path = path
        self.apiDownloadLink = apiDownloadLink
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.path = try values.decodeIfPresent(String.self, forKey: "path")
        self.apiDownloadLink = try values.decodeIfPresent(String.self, forKey: "apiDownloadLink")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(path, forKey: "path")
        try values.encodeIfPresent(apiDownloadLink, forKey: "apiDownloadLink")
    }
}
