// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import HTTPHeaders
import URLQueryEncoder

extension Paths.DataPolicies {
    public var spaces: Spaces {
        Spaces(path: path + "/spaces")
    }

    public struct Spaces {
        /// Path: `/data-policies/spaces`
        public let path: String

        /// Get spaces with data policies
        ///
        /// Returns all spaces. The results will be sorted by id ascending. The number of results is limited by the `limit` parameter and
        /// additional results (if available) will be available through the `next` URL present in the `Link` response header.
        /// 
        /// **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:
        /// Only apps can make this request.
        /// Permission to access the Confluence site ('Can use' global permission).
        /// Only spaces that the app has permission to view will be returned.
        public func get(parameters: GetParameters? = nil) -> Request<GetResponse> {
            Request(path: path, method: "GET", query: parameters?.asQuery, id: "getDataPolicySpaces")
        }

        /// MultiEntityResult<DataPolicySpace>
        public struct GetResponse: Decodable {
            public var results: [ConfluenceKit.DataPolicySpace]?
            public var links: ConfluenceKit.MultiEntityLinks?

            public init(results: [ConfluenceKit.DataPolicySpace]? = nil, links: ConfluenceKit.MultiEntityLinks? = nil) {
                self.results = results
                self.links = links
            }

            public init(from decoder: Decoder) throws {
                let values = try decoder.container(keyedBy: StringCodingKey.self)
                self.results = try values.decodeIfPresent([ConfluenceKit.DataPolicySpace].self, forKey: "results")
                self.links = try values.decodeIfPresent(ConfluenceKit.MultiEntityLinks.self, forKey: "_links")
            }
        }

        public enum GetResponseHeaders {
            /// This header contains URL(s) within angle brackets and a relation description for each URL, describing how the provided URL relates to the incoming request's URL. 
            /// For example, rel="next" would be the URL necessary to get the next page of information. Example response header format: `Link: </wiki/api/v2/spaces?cursor=<opaque cursor token>>; rel="next", <https://site.atlassian.net/wiki>; rel="base"`
            public static let link = HTTPHeader<String>(field: "Link")
        }

        public struct GetParameters {
            public var ids: [Int64]?
            public var keys: [String]?
            /// The sort fields for spaces. The default sort direction is ascending. To sort in descending order, append a `-` character before the sort field. For example, `fieldName` or `-fieldName`.
            public var sort: Sort?
            public var cursor: String?
            public var limit: Int32?

            /// The sort fields for spaces. The default sort direction is ascending. To sort in descending order, append a `-` character before the sort field. For example, `fieldName` or `-fieldName`.
            public enum Sort: String, Codable, CaseIterable {
                case id
                case minusid = "-id"
                case key
                case minuskey = "-key"
                case name
                case minusname = "-name"
            }

            public init(ids: [Int64]? = nil, keys: [String]? = nil, sort: Sort? = nil, cursor: String? = nil, limit: Int32? = nil) {
                self.ids = ids
                self.keys = keys
                self.sort = sort
                self.cursor = cursor
                self.limit = limit
            }

            public var asQuery: [(String, String?)] {
                let encoder = URLQueryEncoder()
                encoder.encode(ids, forKey: "ids")
                encoder.encode(keys, forKey: "keys")
                encoder.encode(sort, forKey: "sort")
                encoder.encode(cursor, forKey: "cursor")
                encoder.encode(limit, forKey: "limit")
                return encoder.items
            }
        }
    }
}
