// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import HTTPHeaders
import URLQueryEncoder

extension Paths {
    public static var pages: Pages {
        Pages(path: "/pages")
    }

    public struct Pages {
        /// Path: `/pages`
        public let path: String

        /// Get pages
        ///
        /// Returns all pages. The number of results is limited by the `limit` parameter and additional results (if available)
        /// will be available through the `next` URL present in the `Link` response header.
        /// 
        /// **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:
        /// Permission to access the Confluence site ('Can use' global permission).
        /// Only pages that the user has permission to view will be returned.
        public func get(parameters: GetParameters? = nil) -> Request<GetResponse> {
            Request(path: path, method: "GET", query: parameters?.asQuery, id: "getPages")
        }

        /// MultiEntityResult<Page>
        public struct GetResponse: Decodable {
            public var results: [ConfluenceKit.PageBulk]?
            public var links: ConfluenceKit.MultiEntityLinks?

            public init(results: [ConfluenceKit.PageBulk]? = nil, links: ConfluenceKit.MultiEntityLinks? = nil) {
                self.results = results
                self.links = links
            }

            public init(from decoder: Decoder) throws {
                let values = try decoder.container(keyedBy: StringCodingKey.self)
                self.results = try values.decodeIfPresent([ConfluenceKit.PageBulk].self, forKey: "results")
                self.links = try values.decodeIfPresent(ConfluenceKit.MultiEntityLinks.self, forKey: "_links")
            }
        }

        public enum GetResponseHeaders {
            /// This header contains URL(s) within angle brackets and a relation description for each URL, describing how the provided URL relates to the incoming request's URL. For example, rel="next" would be the URL necessary to get the next page of information. Example response header format: `Link: </wiki/api/v2/pages?cursor=<opaque cursor token>>; rel="next", <https://site.atlassian.net/wiki>; rel="base"`
            public static let link = HTTPHeader<String>(field: "Link")
        }

        public struct GetParameters {
            public var id: [Int64]?
            public var spaceID: [Int64]?
            /// The sort fields for pages. The default sort direction is ascending. To sort in descending order, append a `-` character before the sort field. For example, `fieldName` or `-fieldName`.
            public var sort: Sort?
            public var status: [Status]?
            public var title: String?
            /// The primary formats a body can be represented as. A subset of BodyRepresentation. These formats are the only allowed formats in certain use cases.
            public var bodyFormat: BodyFormat?
            public var cursor: String?
            public var limit: Int32?

            /// The sort fields for pages. The default sort direction is ascending. To sort in descending order, append a `-` character before the sort field. For example, `fieldName` or `-fieldName`.
            public enum Sort: String, Codable, CaseIterable {
                case id
                case minusid = "-id"
                case createdDate = "created-date"
                case minuscreatedDate = "-created-date"
                case modifiedDate = "modified-date"
                case minusmodifiedDate = "-modified-date"
                case title
                case minustitle = "-title"
            }

            public enum Status: String, Codable, CaseIterable {
                case current
                case archived
                case deleted
                case trashed
            }

            /// The primary formats a body can be represented as. A subset of BodyRepresentation. These formats are the only allowed formats in certain use cases.
            public enum BodyFormat: String, Codable, CaseIterable {
                case storage
                case atlasDocFormat = "atlas_doc_format"
            }

            public init(id: [Int64]? = nil, spaceID: [Int64]? = nil, sort: Sort? = nil, status: [Status]? = nil, title: String? = nil, bodyFormat: BodyFormat? = nil, cursor: String? = nil, limit: Int32? = nil) {
                self.id = id
                self.spaceID = spaceID
                self.sort = sort
                self.status = status
                self.title = title
                self.bodyFormat = bodyFormat
                self.cursor = cursor
                self.limit = limit
            }

            public var asQuery: [(String, String?)] {
                let encoder = URLQueryEncoder()
                encoder.encode(id, forKey: "id")
                encoder.encode(spaceID, forKey: "space-id")
                encoder.encode(sort, forKey: "sort")
                encoder.encode(status, forKey: "status")
                encoder.encode(title, forKey: "title")
                encoder.encode(bodyFormat, forKey: "body-format")
                encoder.encode(cursor, forKey: "cursor")
                encoder.encode(limit, forKey: "limit")
                return encoder.items
            }
        }

        /// Create page
        ///
        /// Creates a page in the space.
        /// 
        /// Pages are created as published by default unless specified as a draft in the status field. If creating a published page, the title must be specified.
        /// 
        /// **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:
        /// Permission to view the corresponding space. Permission to create a page in the space.
        public func post(parameters: PostParameters? = nil, _ body: PostRequest) -> Request<PostResponse> {
            Request(path: path, method: "POST", query: parameters?.asQuery, body: body, id: "createPage")
        }

        public struct PostResponse: Decodable {
            /// ID of the page.
            public var id: String?
            /// The status of the content.
            public var status: ConfluenceKit.ContentStatus?
            /// Title of the page.
            public var title: String?
            /// ID of the space the page is in.
            public var spaceID: String?
            /// ID of the parent page, or null if there is no parent page.
            public var parentID: String?
            /// Content type of the parent, or null if there is no parent.
            public var parentType: ConfluenceKit.ParentContentType?
            /// Position of child page within the given parent page tree.
            public var position: Int32?
            /// The account ID of the user who created this page originally.
            public var authorID: String?
            /// The account ID of the user who owns this page.
            public var ownerID: String?
            /// The account ID of the user who owned this page previously, or null if there is no previous owner.
            public var lastOwnerID: String?
            /// Date and time when the page was created. In format "YYYY-MM-DDTHH:mm:ss.sssZ".
            public var createdAt: Date?
            public var version: ConfluenceKit.Version?
            /// Contains fields for each representation type requested.
            public var body: ConfluenceKit.BodySingle?
            public var labels: Labels?
            public var properties: Properties?
            public var operations: Operations?
            public var likes: Likes?
            public var versions: Versions?
            /// Whether the page has been favorited by the current user.
            public var isFavoritedByCurrentUser: Bool?
            public var links: ConfluenceKit.AbstractPageLinks?

            public struct Labels: Decodable {
                public var results: [ConfluenceKit.Label]?
                public var meta: ConfluenceKit.OptionalFieldMeta?
                public var links: ConfluenceKit.OptionalFieldLinks?

                public init(results: [ConfluenceKit.Label]? = nil, meta: ConfluenceKit.OptionalFieldMeta? = nil, links: ConfluenceKit.OptionalFieldLinks? = nil) {
                    self.results = results
                    self.meta = meta
                    self.links = links
                }

                public init(from decoder: Decoder) throws {
                    let values = try decoder.container(keyedBy: StringCodingKey.self)
                    self.results = try values.decodeIfPresent([ConfluenceKit.Label].self, forKey: "results")
                    self.meta = try values.decodeIfPresent(ConfluenceKit.OptionalFieldMeta.self, forKey: "meta")
                    self.links = try values.decodeIfPresent(ConfluenceKit.OptionalFieldLinks.self, forKey: "_links")
                }
            }

            public struct Properties: Decodable {
                public var results: [ConfluenceKit.ContentProperty]?
                public var meta: ConfluenceKit.OptionalFieldMeta?
                public var links: ConfluenceKit.OptionalFieldLinks?

                public init(results: [ConfluenceKit.ContentProperty]? = nil, meta: ConfluenceKit.OptionalFieldMeta? = nil, links: ConfluenceKit.OptionalFieldLinks? = nil) {
                    self.results = results
                    self.meta = meta
                    self.links = links
                }

                public init(from decoder: Decoder) throws {
                    let values = try decoder.container(keyedBy: StringCodingKey.self)
                    self.results = try values.decodeIfPresent([ConfluenceKit.ContentProperty].self, forKey: "results")
                    self.meta = try values.decodeIfPresent(ConfluenceKit.OptionalFieldMeta.self, forKey: "meta")
                    self.links = try values.decodeIfPresent(ConfluenceKit.OptionalFieldLinks.self, forKey: "_links")
                }
            }

            public struct Operations: Decodable {
                public var results: [ConfluenceKit.Operation]?
                public var meta: ConfluenceKit.OptionalFieldMeta?
                public var links: ConfluenceKit.OptionalFieldLinks?

                public init(results: [ConfluenceKit.Operation]? = nil, meta: ConfluenceKit.OptionalFieldMeta? = nil, links: ConfluenceKit.OptionalFieldLinks? = nil) {
                    self.results = results
                    self.meta = meta
                    self.links = links
                }

                public init(from decoder: Decoder) throws {
                    let values = try decoder.container(keyedBy: StringCodingKey.self)
                    self.results = try values.decodeIfPresent([ConfluenceKit.Operation].self, forKey: "results")
                    self.meta = try values.decodeIfPresent(ConfluenceKit.OptionalFieldMeta.self, forKey: "meta")
                    self.links = try values.decodeIfPresent(ConfluenceKit.OptionalFieldLinks.self, forKey: "_links")
                }
            }

            public struct Likes: Decodable {
                public var results: [ConfluenceKit.Like]?
                public var meta: ConfluenceKit.OptionalFieldMeta?
                public var links: ConfluenceKit.OptionalFieldLinks?

                public init(results: [ConfluenceKit.Like]? = nil, meta: ConfluenceKit.OptionalFieldMeta? = nil, links: ConfluenceKit.OptionalFieldLinks? = nil) {
                    self.results = results
                    self.meta = meta
                    self.links = links
                }

                public init(from decoder: Decoder) throws {
                    let values = try decoder.container(keyedBy: StringCodingKey.self)
                    self.results = try values.decodeIfPresent([ConfluenceKit.Like].self, forKey: "results")
                    self.meta = try values.decodeIfPresent(ConfluenceKit.OptionalFieldMeta.self, forKey: "meta")
                    self.links = try values.decodeIfPresent(ConfluenceKit.OptionalFieldLinks.self, forKey: "_links")
                }
            }

            public struct Versions: Decodable {
                public var results: [ConfluenceKit.Version]?
                public var meta: ConfluenceKit.OptionalFieldMeta?
                public var links: ConfluenceKit.OptionalFieldLinks?

                public init(results: [ConfluenceKit.Version]? = nil, meta: ConfluenceKit.OptionalFieldMeta? = nil, links: ConfluenceKit.OptionalFieldLinks? = nil) {
                    self.results = results
                    self.meta = meta
                    self.links = links
                }

                public init(from decoder: Decoder) throws {
                    let values = try decoder.container(keyedBy: StringCodingKey.self)
                    self.results = try values.decodeIfPresent([ConfluenceKit.Version].self, forKey: "results")
                    self.meta = try values.decodeIfPresent(ConfluenceKit.OptionalFieldMeta.self, forKey: "meta")
                    self.links = try values.decodeIfPresent(ConfluenceKit.OptionalFieldLinks.self, forKey: "_links")
                }
            }

            public init(id: String? = nil, status: ConfluenceKit.ContentStatus? = nil, title: String? = nil, spaceID: String? = nil, parentID: String? = nil, parentType: ConfluenceKit.ParentContentType? = nil, position: Int32? = nil, authorID: String? = nil, ownerID: String? = nil, lastOwnerID: String? = nil, createdAt: Date? = nil, version: ConfluenceKit.Version? = nil, body: ConfluenceKit.BodySingle? = nil, labels: Labels? = nil, properties: Properties? = nil, operations: Operations? = nil, likes: Likes? = nil, versions: Versions? = nil, isFavoritedByCurrentUser: Bool? = nil, links: ConfluenceKit.AbstractPageLinks? = nil) {
                self.id = id
                self.status = status
                self.title = title
                self.spaceID = spaceID
                self.parentID = parentID
                self.parentType = parentType
                self.position = position
                self.authorID = authorID
                self.ownerID = ownerID
                self.lastOwnerID = lastOwnerID
                self.createdAt = createdAt
                self.version = version
                self.body = body
                self.labels = labels
                self.properties = properties
                self.operations = operations
                self.likes = likes
                self.versions = versions
                self.isFavoritedByCurrentUser = isFavoritedByCurrentUser
                self.links = links
            }

            public init(from decoder: Decoder) throws {
                let values = try decoder.container(keyedBy: StringCodingKey.self)
                self.id = try values.decodeIfPresent(String.self, forKey: "id")
                self.status = try values.decodeIfPresent(ConfluenceKit.ContentStatus.self, forKey: "status")
                self.title = try values.decodeIfPresent(String.self, forKey: "title")
                self.spaceID = try values.decodeIfPresent(String.self, forKey: "spaceId")
                self.parentID = try values.decodeIfPresent(String.self, forKey: "parentId")
                self.parentType = try values.decodeIfPresent(ConfluenceKit.ParentContentType.self, forKey: "parentType")
                self.position = try values.decodeIfPresent(Int32.self, forKey: "position")
                self.authorID = try values.decodeIfPresent(String.self, forKey: "authorId")
                self.ownerID = try values.decodeIfPresent(String.self, forKey: "ownerId")
                self.lastOwnerID = try values.decodeIfPresent(String.self, forKey: "lastOwnerId")
                self.createdAt = try values.decodeIfPresent(Date.self, forKey: "createdAt")
                self.version = try values.decodeIfPresent(ConfluenceKit.Version.self, forKey: "version")
                self.body = try values.decodeIfPresent(ConfluenceKit.BodySingle.self, forKey: "body")
                self.labels = try values.decodeIfPresent(Labels.self, forKey: "labels")
                self.properties = try values.decodeIfPresent(Properties.self, forKey: "properties")
                self.operations = try values.decodeIfPresent(Operations.self, forKey: "operations")
                self.likes = try values.decodeIfPresent(Likes.self, forKey: "likes")
                self.versions = try values.decodeIfPresent(Versions.self, forKey: "versions")
                self.isFavoritedByCurrentUser = try values.decodeIfPresent(Bool.self, forKey: "isFavoritedByCurrentUser")
                self.links = try values.decodeIfPresent(ConfluenceKit.AbstractPageLinks.self, forKey: "_links")
            }
        }

        public struct PostParameters {
            public var isEmbedded: Bool?
            public var isPrivate: Bool?
            public var isRootLevel: Bool?

            public init(isEmbedded: Bool? = nil, isPrivate: Bool? = nil, isRootLevel: Bool? = nil) {
                self.isEmbedded = isEmbedded
                self.isPrivate = isPrivate
                self.isRootLevel = isRootLevel
            }

            public var asQuery: [(String, String?)] {
                let encoder = URLQueryEncoder()
                encoder.encode(isEmbedded, forKey: "embedded")
                encoder.encode(isPrivate, forKey: "private")
                encoder.encode(isRootLevel, forKey: "root-level")
                return encoder.items
            }
        }

        public struct PostRequest: Encodable {
            /// ID of the space.
            public var spaceID: String
            /// The status of the page, published or draft.
            public var status: Status?
            /// Title of the page, required if page status is not draft.
            public var title: String?
            /// The parent content ID of the page. If the `root-level` query parameter is set to false and a value is 
            /// not supplied for this parameter, then the space homepage's ID will be used. If the `root-level` query 
            /// parameter is set to true, then a value may not be supplied for this parameter.
            public var parentID: String?
            public var body: Body?

            /// The status of the page, published or draft.
            public enum Status: String, Codable, CaseIterable {
                case current
                case draft
            }

            public enum Body: Encodable {
                case pageBodyWrite(ConfluenceKit.PageBodyWrite)
                case pageNestedBodyWrite(ConfluenceKit.PageNestedBodyWrite)

                public func encode(to encoder: Encoder) throws {
                    var container = encoder.singleValueContainer()
                    switch self {
                    case .pageBodyWrite(let value): try container.encode(value)
                    case .pageNestedBodyWrite(let value): try container.encode(value)
                    }
                }
            }

            public init(spaceID: String, status: Status? = nil, title: String? = nil, parentID: String? = nil, body: Body? = nil) {
                self.spaceID = spaceID
                self.status = status
                self.title = title
                self.parentID = parentID
                self.body = body
            }

            public func encode(to encoder: Encoder) throws {
                var values = encoder.container(keyedBy: StringCodingKey.self)
                try values.encode(spaceID, forKey: "spaceId")
                try values.encodeIfPresent(status, forKey: "status")
                try values.encodeIfPresent(title, forKey: "title")
                try values.encodeIfPresent(parentID, forKey: "parentId")
                try values.encodeIfPresent(body, forKey: "body")
            }
        }
    }
}
