// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import HTTPHeaders
import URLQueryEncoder

extension Paths.FooterComments.WithID.Versions {
    public func versionNumber(_ versionNumber: Int) -> WithVersionNumber {
        WithVersionNumber(path: "\(path)/\(versionNumber)")
    }

    public struct WithVersionNumber {
        /// Path: `/footer-comments/{id}/versions/{version-number}`
        public let path: String

        /// Get version details for footer comment version
        ///
        /// Retrieves version details for the specified footer comment version.
        /// 
        /// **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:
        /// Permission to view the content of the page or blog post and its corresponding space.
        public var get: Request<ConfluenceKit.DetailedVersion> {
            Request(path: path, method: "GET", id: "getFooterCommentVersionDetails")
        }
    }
}
