// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import HTTPHeaders
import URLQueryEncoder

extension Paths {
    public static var classificationLevels: ClassificationLevels {
        ClassificationLevels(path: "/classification-levels")
    }

    public struct ClassificationLevels {
        /// Path: `/classification-levels`
        public let path: String

        /// Get list of classification levels
        ///
        /// Returns a list of [classification levels](https://developer.atlassian.com/cloud/admin/dlp/rest/intro/#Classification%20level) 
        /// available.
        /// 
        /// **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:
        /// 'Permission to access the Confluence site ('Can use' global permission).
        public var get: Request<[ConfluenceKit.ClassificationLevel]> {
            Request(path: path, method: "GET", id: "getClassificationLevels")
        }
    }
}
