// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import HTTPHeaders
import URLQueryEncoder

extension Paths.Blogposts {
    public func blogpostID(_ blogpostID: Int) -> WithBlogpostID {
        WithBlogpostID(path: "\(path)/\(blogpostID)")
    }

    public struct WithBlogpostID {
        /// Path: `/blogposts/{blogpost-id}`
        public let path: String
    }
}
