// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import HTTPHeaders
import URLQueryEncoder

extension Paths.Spaces {
    public func spaceID(_ spaceID: Int) -> WithSpaceID {
        WithSpaceID(path: "\(path)/\(spaceID)")
    }

    public struct WithSpaceID {
        /// Path: `/spaces/{space-id}`
        public let path: String
    }
}
