// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import HTTPHeaders
import URLQueryEncoder

extension Paths {
    public static var comments: Comments {
        Comments(path: "/comments")
    }

    public struct Comments {
        /// Path: `/comments`
        public let path: String
    }
}
