// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import HTTPHeaders
import URLQueryEncoder

extension Paths.Spaces.WithID {
    public var content: Content {
        Content(path: path + "/content")
    }

    public struct Content {
        /// Path: `/spaces/{id}/content`
        public let path: String
    }
}
