// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import HTTPHeaders
import URLQueryEncoder

extension Paths.Whiteboards {
    public func whiteboardID(_ whiteboardID: Int) -> WithWhiteboardID {
        WithWhiteboardID(path: "\(path)/\(whiteboardID)")
    }

    public struct WithWhiteboardID {
        /// Path: `/whiteboards/{whiteboard-id}`
        public let path: String
    }
}
