// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import HTTPHeaders
import URLQueryEncoder

extension Paths.Databases {
    public func databaseID(_ databaseID: Int) -> WithDatabaseID {
        WithDatabaseID(path: "\(path)/\(databaseID)")
    }

    public struct WithDatabaseID {
        /// Path: `/databases/{database-id}`
        public let path: String
    }
}
