// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import HTTPHeaders
import URLQueryEncoder

extension Paths.CustomContent {
    public func id(_ id: Int) -> WithID {
        WithID(path: "\(path)/\(id)")
    }

    public struct WithID {
        /// Path: `/custom-content/{id}`
        public let path: String

        /// Get custom content by id
        ///
        /// Returns a specific piece of custom content. 
        /// 
        /// **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:
        /// Permission to view the custom content, the container of the custom content, and the corresponding space (if different from the container).
        public func get(parameters: GetParameters? = nil) -> Request<GetResponse> {
            Request(path: path, method: "GET", query: parameters?.asQuery, id: "getCustomContentById")
        }

        public struct GetResponse: Decodable {
            /// ID of the custom content.
            public var id: String?
            /// The type of custom content.
            public var type: String?
            /// The status of the content.
            public var status: ConfluenceKit.ContentStatus?
            /// Title of the custom content.
            public var title: String?
            /// ID of the space the custom content is in.
            /// 
            /// Note: This is always returned, regardless of if the custom content has a container that is a space.
            public var spaceID: String?
            /// ID of the containing page.
            /// 
            /// Note: This is only returned if the custom content has a container that is a page.
            public var pageID: String?
            /// ID of the containing blog post.
            /// 
            /// Note: This is only returned if the custom content has a container that is a blog post.
            public var blogPostID: String?
            /// ID of the containing custom content.
            /// 
            /// Note: This is only returned if the custom content has a container that is custom content.
            public var customContentID: String?
            /// The account ID of the user who created this custom content originally.
            public var authorID: String?
            /// Date and time when the custom content was created. In format "YYYY-MM-DDTHH:mm:ss.sssZ".
            public var createdAt: Date?
            public var version: ConfluenceKit.Version?
            public var labels: Labels?
            public var properties: Properties?
            public var operations: Operations?
            public var versions: Versions?
            /// Contains fields for each representation type requested.
            public var body: ConfluenceKit.CustomContentBodySingle?
            public var links: ConfluenceKit.CustomContentLinks?

            public struct Labels: Decodable {
                public var results: [ConfluenceKit.Label]?
                public var meta: ConfluenceKit.OptionalFieldMeta?
                public var links: ConfluenceKit.OptionalFieldLinks?

                public init(results: [ConfluenceKit.Label]? = nil, meta: ConfluenceKit.OptionalFieldMeta? = nil, links: ConfluenceKit.OptionalFieldLinks? = nil) {
                    self.results = results
                    self.meta = meta
                    self.links = links
                }

                public init(from decoder: Decoder) throws {
                    let values = try decoder.container(keyedBy: StringCodingKey.self)
                    self.results = try values.decodeIfPresent([ConfluenceKit.Label].self, forKey: "results")
                    self.meta = try values.decodeIfPresent(ConfluenceKit.OptionalFieldMeta.self, forKey: "meta")
                    self.links = try values.decodeIfPresent(ConfluenceKit.OptionalFieldLinks.self, forKey: "_links")
                }
            }

            public struct Properties: Decodable {
                public var results: [ConfluenceKit.ContentProperty]?
                public var meta: ConfluenceKit.OptionalFieldMeta?
                public var links: ConfluenceKit.OptionalFieldLinks?

                public init(results: [ConfluenceKit.ContentProperty]? = nil, meta: ConfluenceKit.OptionalFieldMeta? = nil, links: ConfluenceKit.OptionalFieldLinks? = nil) {
                    self.results = results
                    self.meta = meta
                    self.links = links
                }

                public init(from decoder: Decoder) throws {
                    let values = try decoder.container(keyedBy: StringCodingKey.self)
                    self.results = try values.decodeIfPresent([ConfluenceKit.ContentProperty].self, forKey: "results")
                    self.meta = try values.decodeIfPresent(ConfluenceKit.OptionalFieldMeta.self, forKey: "meta")
                    self.links = try values.decodeIfPresent(ConfluenceKit.OptionalFieldLinks.self, forKey: "_links")
                }
            }

            public struct Operations: Decodable {
                public var results: [ConfluenceKit.Operation]?
                public var meta: ConfluenceKit.OptionalFieldMeta?
                public var links: ConfluenceKit.OptionalFieldLinks?

                public init(results: [ConfluenceKit.Operation]? = nil, meta: ConfluenceKit.OptionalFieldMeta? = nil, links: ConfluenceKit.OptionalFieldLinks? = nil) {
                    self.results = results
                    self.meta = meta
                    self.links = links
                }

                public init(from decoder: Decoder) throws {
                    let values = try decoder.container(keyedBy: StringCodingKey.self)
                    self.results = try values.decodeIfPresent([ConfluenceKit.Operation].self, forKey: "results")
                    self.meta = try values.decodeIfPresent(ConfluenceKit.OptionalFieldMeta.self, forKey: "meta")
                    self.links = try values.decodeIfPresent(ConfluenceKit.OptionalFieldLinks.self, forKey: "_links")
                }
            }

            public struct Versions: Decodable {
                public var results: [ConfluenceKit.Version]?
                public var meta: ConfluenceKit.OptionalFieldMeta?
                public var links: ConfluenceKit.OptionalFieldLinks?

                public init(results: [ConfluenceKit.Version]? = nil, meta: ConfluenceKit.OptionalFieldMeta? = nil, links: ConfluenceKit.OptionalFieldLinks? = nil) {
                    self.results = results
                    self.meta = meta
                    self.links = links
                }

                public init(from decoder: Decoder) throws {
                    let values = try decoder.container(keyedBy: StringCodingKey.self)
                    self.results = try values.decodeIfPresent([ConfluenceKit.Version].self, forKey: "results")
                    self.meta = try values.decodeIfPresent(ConfluenceKit.OptionalFieldMeta.self, forKey: "meta")
                    self.links = try values.decodeIfPresent(ConfluenceKit.OptionalFieldLinks.self, forKey: "_links")
                }
            }

            public init(id: String? = nil, type: String? = nil, status: ConfluenceKit.ContentStatus? = nil, title: String? = nil, spaceID: String? = nil, pageID: String? = nil, blogPostID: String? = nil, customContentID: String? = nil, authorID: String? = nil, createdAt: Date? = nil, version: ConfluenceKit.Version? = nil, labels: Labels? = nil, properties: Properties? = nil, operations: Operations? = nil, versions: Versions? = nil, body: ConfluenceKit.CustomContentBodySingle? = nil, links: ConfluenceKit.CustomContentLinks? = nil) {
                self.id = id
                self.type = type
                self.status = status
                self.title = title
                self.spaceID = spaceID
                self.pageID = pageID
                self.blogPostID = blogPostID
                self.customContentID = customContentID
                self.authorID = authorID
                self.createdAt = createdAt
                self.version = version
                self.labels = labels
                self.properties = properties
                self.operations = operations
                self.versions = versions
                self.body = body
                self.links = links
            }

            public init(from decoder: Decoder) throws {
                let values = try decoder.container(keyedBy: StringCodingKey.self)
                self.id = try values.decodeIfPresent(String.self, forKey: "id")
                self.type = try values.decodeIfPresent(String.self, forKey: "type")
                self.status = try values.decodeIfPresent(ConfluenceKit.ContentStatus.self, forKey: "status")
                self.title = try values.decodeIfPresent(String.self, forKey: "title")
                self.spaceID = try values.decodeIfPresent(String.self, forKey: "spaceId")
                self.pageID = try values.decodeIfPresent(String.self, forKey: "pageId")
                self.blogPostID = try values.decodeIfPresent(String.self, forKey: "blogPostId")
                self.customContentID = try values.decodeIfPresent(String.self, forKey: "customContentId")
                self.authorID = try values.decodeIfPresent(String.self, forKey: "authorId")
                self.createdAt = try values.decodeIfPresent(Date.self, forKey: "createdAt")
                self.version = try values.decodeIfPresent(ConfluenceKit.Version.self, forKey: "version")
                self.labels = try values.decodeIfPresent(Labels.self, forKey: "labels")
                self.properties = try values.decodeIfPresent(Properties.self, forKey: "properties")
                self.operations = try values.decodeIfPresent(Operations.self, forKey: "operations")
                self.versions = try values.decodeIfPresent(Versions.self, forKey: "versions")
                self.body = try values.decodeIfPresent(ConfluenceKit.CustomContentBodySingle.self, forKey: "body")
                self.links = try values.decodeIfPresent(ConfluenceKit.CustomContentLinks.self, forKey: "_links")
            }
        }

        public struct GetParameters {
            /// The formats a custom content body can be represented as. A subset of BodyRepresentation.
            public var bodyFormat: BodyFormat?
            public var version: Int?
            public var isIncludeLabels: Bool?
            public var isIncludeProperties: Bool?
            public var isIncludeOperations: Bool?
            public var isIncludeVersions: Bool?
            public var isIncludeVersion: Bool?

            /// The formats a custom content body can be represented as. A subset of BodyRepresentation.
            public enum BodyFormat: String, Codable, CaseIterable {
                case raw
                case storage
                case atlasDocFormat = "atlas_doc_format"
                case view
                case exportView = "export_view"
                case anonymousExportView = "anonymous_export_view"
            }

            public init(bodyFormat: BodyFormat? = nil, version: Int? = nil, isIncludeLabels: Bool? = nil, isIncludeProperties: Bool? = nil, isIncludeOperations: Bool? = nil, isIncludeVersions: Bool? = nil, isIncludeVersion: Bool? = nil) {
                self.bodyFormat = bodyFormat
                self.version = version
                self.isIncludeLabels = isIncludeLabels
                self.isIncludeProperties = isIncludeProperties
                self.isIncludeOperations = isIncludeOperations
                self.isIncludeVersions = isIncludeVersions
                self.isIncludeVersion = isIncludeVersion
            }

            public var asQuery: [(String, String?)] {
                let encoder = URLQueryEncoder()
                encoder.encode(bodyFormat, forKey: "body-format")
                encoder.encode(version, forKey: "version")
                encoder.encode(isIncludeLabels, forKey: "include-labels")
                encoder.encode(isIncludeProperties, forKey: "include-properties")
                encoder.encode(isIncludeOperations, forKey: "include-operations")
                encoder.encode(isIncludeVersions, forKey: "include-versions")
                encoder.encode(isIncludeVersion, forKey: "include-version")
                return encoder.items
            }
        }

        /// Update custom content
        ///
        /// Update a custom content by id.
        /// 
        /// `spaceId` is always required and maximum one of `pageId`, `blogPostId`, or `customContentId` is allowed in the request body.
        /// **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:
        /// Permission to view the content of the page or blogpost and its corresponding space. Permission to update custom content in the space.
        public func put(_ body: PutRequest) -> Request<PutResponse> {
            Request(path: path, method: "PUT", body: body, id: "updateCustomContent")
        }

        public struct PutResponse: Decodable {
            /// ID of the custom content.
            public var id: String?
            /// The type of custom content.
            public var type: String?
            /// The status of the content.
            public var status: ConfluenceKit.ContentStatus?
            /// Title of the custom content.
            public var title: String?
            /// ID of the space the custom content is in.
            /// 
            /// Note: This is always returned, regardless of if the custom content has a container that is a space.
            public var spaceID: String?
            /// ID of the containing page.
            /// 
            /// Note: This is only returned if the custom content has a container that is a page.
            public var pageID: String?
            /// ID of the containing blog post.
            /// 
            /// Note: This is only returned if the custom content has a container that is a blog post.
            public var blogPostID: String?
            /// ID of the containing custom content.
            /// 
            /// Note: This is only returned if the custom content has a container that is custom content.
            public var customContentID: String?
            /// The account ID of the user who created this custom content originally.
            public var authorID: String?
            /// Date and time when the custom content was created. In format "YYYY-MM-DDTHH:mm:ss.sssZ".
            public var createdAt: Date?
            public var version: ConfluenceKit.Version?
            public var labels: Labels?
            public var properties: Properties?
            public var operations: Operations?
            public var versions: Versions?
            /// Contains fields for each representation type requested.
            public var body: ConfluenceKit.CustomContentBodySingle?
            public var links: ConfluenceKit.CustomContentLinks?

            public struct Labels: Decodable {
                public var results: [ConfluenceKit.Label]?
                public var meta: ConfluenceKit.OptionalFieldMeta?
                public var links: ConfluenceKit.OptionalFieldLinks?

                public init(results: [ConfluenceKit.Label]? = nil, meta: ConfluenceKit.OptionalFieldMeta? = nil, links: ConfluenceKit.OptionalFieldLinks? = nil) {
                    self.results = results
                    self.meta = meta
                    self.links = links
                }

                public init(from decoder: Decoder) throws {
                    let values = try decoder.container(keyedBy: StringCodingKey.self)
                    self.results = try values.decodeIfPresent([ConfluenceKit.Label].self, forKey: "results")
                    self.meta = try values.decodeIfPresent(ConfluenceKit.OptionalFieldMeta.self, forKey: "meta")
                    self.links = try values.decodeIfPresent(ConfluenceKit.OptionalFieldLinks.self, forKey: "_links")
                }
            }

            public struct Properties: Decodable {
                public var results: [ConfluenceKit.ContentProperty]?
                public var meta: ConfluenceKit.OptionalFieldMeta?
                public var links: ConfluenceKit.OptionalFieldLinks?

                public init(results: [ConfluenceKit.ContentProperty]? = nil, meta: ConfluenceKit.OptionalFieldMeta? = nil, links: ConfluenceKit.OptionalFieldLinks? = nil) {
                    self.results = results
                    self.meta = meta
                    self.links = links
                }

                public init(from decoder: Decoder) throws {
                    let values = try decoder.container(keyedBy: StringCodingKey.self)
                    self.results = try values.decodeIfPresent([ConfluenceKit.ContentProperty].self, forKey: "results")
                    self.meta = try values.decodeIfPresent(ConfluenceKit.OptionalFieldMeta.self, forKey: "meta")
                    self.links = try values.decodeIfPresent(ConfluenceKit.OptionalFieldLinks.self, forKey: "_links")
                }
            }

            public struct Operations: Decodable {
                public var results: [ConfluenceKit.Operation]?
                public var meta: ConfluenceKit.OptionalFieldMeta?
                public var links: ConfluenceKit.OptionalFieldLinks?

                public init(results: [ConfluenceKit.Operation]? = nil, meta: ConfluenceKit.OptionalFieldMeta? = nil, links: ConfluenceKit.OptionalFieldLinks? = nil) {
                    self.results = results
                    self.meta = meta
                    self.links = links
                }

                public init(from decoder: Decoder) throws {
                    let values = try decoder.container(keyedBy: StringCodingKey.self)
                    self.results = try values.decodeIfPresent([ConfluenceKit.Operation].self, forKey: "results")
                    self.meta = try values.decodeIfPresent(ConfluenceKit.OptionalFieldMeta.self, forKey: "meta")
                    self.links = try values.decodeIfPresent(ConfluenceKit.OptionalFieldLinks.self, forKey: "_links")
                }
            }

            public struct Versions: Decodable {
                public var results: [ConfluenceKit.Version]?
                public var meta: ConfluenceKit.OptionalFieldMeta?
                public var links: ConfluenceKit.OptionalFieldLinks?

                public init(results: [ConfluenceKit.Version]? = nil, meta: ConfluenceKit.OptionalFieldMeta? = nil, links: ConfluenceKit.OptionalFieldLinks? = nil) {
                    self.results = results
                    self.meta = meta
                    self.links = links
                }

                public init(from decoder: Decoder) throws {
                    let values = try decoder.container(keyedBy: StringCodingKey.self)
                    self.results = try values.decodeIfPresent([ConfluenceKit.Version].self, forKey: "results")
                    self.meta = try values.decodeIfPresent(ConfluenceKit.OptionalFieldMeta.self, forKey: "meta")
                    self.links = try values.decodeIfPresent(ConfluenceKit.OptionalFieldLinks.self, forKey: "_links")
                }
            }

            public init(id: String? = nil, type: String? = nil, status: ConfluenceKit.ContentStatus? = nil, title: String? = nil, spaceID: String? = nil, pageID: String? = nil, blogPostID: String? = nil, customContentID: String? = nil, authorID: String? = nil, createdAt: Date? = nil, version: ConfluenceKit.Version? = nil, labels: Labels? = nil, properties: Properties? = nil, operations: Operations? = nil, versions: Versions? = nil, body: ConfluenceKit.CustomContentBodySingle? = nil, links: ConfluenceKit.CustomContentLinks? = nil) {
                self.id = id
                self.type = type
                self.status = status
                self.title = title
                self.spaceID = spaceID
                self.pageID = pageID
                self.blogPostID = blogPostID
                self.customContentID = customContentID
                self.authorID = authorID
                self.createdAt = createdAt
                self.version = version
                self.labels = labels
                self.properties = properties
                self.operations = operations
                self.versions = versions
                self.body = body
                self.links = links
            }

            public init(from decoder: Decoder) throws {
                let values = try decoder.container(keyedBy: StringCodingKey.self)
                self.id = try values.decodeIfPresent(String.self, forKey: "id")
                self.type = try values.decodeIfPresent(String.self, forKey: "type")
                self.status = try values.decodeIfPresent(ConfluenceKit.ContentStatus.self, forKey: "status")
                self.title = try values.decodeIfPresent(String.self, forKey: "title")
                self.spaceID = try values.decodeIfPresent(String.self, forKey: "spaceId")
                self.pageID = try values.decodeIfPresent(String.self, forKey: "pageId")
                self.blogPostID = try values.decodeIfPresent(String.self, forKey: "blogPostId")
                self.customContentID = try values.decodeIfPresent(String.self, forKey: "customContentId")
                self.authorID = try values.decodeIfPresent(String.self, forKey: "authorId")
                self.createdAt = try values.decodeIfPresent(Date.self, forKey: "createdAt")
                self.version = try values.decodeIfPresent(ConfluenceKit.Version.self, forKey: "version")
                self.labels = try values.decodeIfPresent(Labels.self, forKey: "labels")
                self.properties = try values.decodeIfPresent(Properties.self, forKey: "properties")
                self.operations = try values.decodeIfPresent(Operations.self, forKey: "operations")
                self.versions = try values.decodeIfPresent(Versions.self, forKey: "versions")
                self.body = try values.decodeIfPresent(ConfluenceKit.CustomContentBodySingle.self, forKey: "body")
                self.links = try values.decodeIfPresent(ConfluenceKit.CustomContentLinks.self, forKey: "_links")
            }
        }

        public enum PutResponseHeaders {
            /// Relative link to updated custom content Example response header format: `location: </wiki/api/v2/custom-content/<id>>`
            public static let location = HTTPHeader<String>(field: "location")
        }

        public struct PutRequest: Encodable {
            /// Id of custom content.
            public var id: String
            /// Type of custom content.
            public var type: String
            /// The status of the custom content.
            public var status: Status
            /// ID of the containing space.
            public var spaceID: String?
            /// ID of the containing page.
            public var pageID: String?
            /// ID of the containing Blog Post.
            public var blogPostID: String?
            /// ID of the containing custom content.
            public var customContentID: String?
            /// Title of the custom content.
            public var title: String
            public var body: Body
            public var version: Version

            /// The status of the custom content.
            public enum Status: String, Codable, CaseIterable {
                case current
            }

            public enum Body: Encodable {
                case customContentBodyWrite(ConfluenceKit.CustomContentBodyWrite)
                case customContentNestedBodyWrite(ConfluenceKit.CustomContentNestedBodyWrite)

                public func encode(to encoder: Encoder) throws {
                    var container = encoder.singleValueContainer()
                    switch self {
                    case .customContentBodyWrite(let value): try container.encode(value)
                    case .customContentNestedBodyWrite(let value): try container.encode(value)
                    }
                }
            }

            public struct Version: Encodable {
                /// The version number, must be incremented by one.
                public var number: Int32?
                /// An optional message to be stored with the version.
                public var message: String?

                public init(number: Int32? = nil, message: String? = nil) {
                    self.number = number
                    self.message = message
                }

                public func encode(to encoder: Encoder) throws {
                    var values = encoder.container(keyedBy: StringCodingKey.self)
                    try values.encodeIfPresent(number, forKey: "number")
                    try values.encodeIfPresent(message, forKey: "message")
                }
            }

            public init(id: String, type: String, status: Status, spaceID: String? = nil, pageID: String? = nil, blogPostID: String? = nil, customContentID: String? = nil, title: String, body: Body, version: Version) {
                self.id = id
                self.type = type
                self.status = status
                self.spaceID = spaceID
                self.pageID = pageID
                self.blogPostID = blogPostID
                self.customContentID = customContentID
                self.title = title
                self.body = body
                self.version = version
            }

            public func encode(to encoder: Encoder) throws {
                var values = encoder.container(keyedBy: StringCodingKey.self)
                try values.encode(id, forKey: "id")
                try values.encode(type, forKey: "type")
                try values.encode(status, forKey: "status")
                try values.encodeIfPresent(spaceID, forKey: "spaceId")
                try values.encodeIfPresent(pageID, forKey: "pageId")
                try values.encodeIfPresent(blogPostID, forKey: "blogPostId")
                try values.encodeIfPresent(customContentID, forKey: "customContentId")
                try values.encode(title, forKey: "title")
                try values.encode(body, forKey: "body")
                try values.encode(version, forKey: "version")
            }
        }

        /// Delete custom content
        ///
        /// Delete a custom content by id.
        /// 
        /// Deleting a custom content will either move it to the trash or permanently delete it (purge it), depending on the apiSupport.
        /// To permanently delete a **trashed** custom content, the endpoint must be called with the following param `purge=true`.
        /// 
        /// **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:
        /// Permission to view the content of the page or blogpost and its corresponding space.
        /// Permission to delete custom content in the space.
        /// Permission to administer the space (if attempting to purge).
        public func delete(isPurge: Bool? = nil) -> Request<Void> {
            Request(path: path, method: "DELETE", query: makeDeleteQuery(isPurge), id: "deleteCustomContent")
        }

        private func makeDeleteQuery(_ isPurge: Bool?) -> [(String, String?)] {
            let encoder = URLQueryEncoder()
            encoder.encode(isPurge, forKey: "purge")
            return encoder.items
        }
    }
}
