// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import HTTPHeaders
import URLQueryEncoder

extension Paths.InlineComments.WithID {
    public var operations: Operations {
        Operations(path: path + "/operations")
    }

    public struct Operations {
        /// Path: `/inline-comments/{id}/operations`
        public let path: String

        /// Get permitted operations for inline comment
        ///
        /// Returns the permitted operations on specific inline comment.
        /// 
        /// **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:
        /// Permission to view the parent content of the inline comment and its corresponding space.
        public var get: Request<ConfluenceKit.PermittedOperationsResponse> {
            Request(path: path, method: "GET", id: "getInlineCommentOperations")
        }
    }
}
