// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import HTTPHeaders
import URLQueryEncoder

extension Paths.Databases.WithID {
    public var classificationLevel: ClassificationLevel {
        ClassificationLevel(path: path + "/classification-level")
    }

    public struct ClassificationLevel {
        /// Path: `/databases/{id}/classification-level`
        public let path: String

        /// Get database classification level
        ///
        /// Returns the [classification level](https://developer.atlassian.com/cloud/admin/dlp/rest/intro/#Classification%20level)
        /// for a specific database.
        /// 
        /// **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:
        /// 'Permission to access the Confluence site ('Can use' global permission) and permission to view the database.
        public var get: Request<ConfluenceKit.ClassificationLevel> {
            Request(path: path, method: "GET", id: "getDatabaseClassificationLevel")
        }

        /// Update database classification level
        ///
        /// Updates the [classification level](https://developer.atlassian.com/cloud/admin/dlp/rest/intro/#Classification%20level)
        /// for a specific database.
        /// 
        /// **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:
        /// 'Permission to access the Confluence site ('Can use' global permission) and permission to edit the database.
        public func put(_ body: PutRequest) -> Request<Void> {
            Request(path: path, method: "PUT", body: body, id: "putDatabaseClassificationLevel")
        }

        public struct PutRequest: Encodable {
            /// The ID of the classification level.
            public var id: String
            /// Status of the content.
            public var status: Status

            /// Status of the content.
            public enum Status: String, Codable, CaseIterable {
                case current
            }

            public init(id: String, status: Status) {
                self.id = id
                self.status = status
            }

            public func encode(to encoder: Encoder) throws {
                var values = encoder.container(keyedBy: StringCodingKey.self)
                try values.encode(id, forKey: "id")
                try values.encode(status, forKey: "status")
            }
        }
    }
}
