// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import HTTPHeaders
import URLQueryEncoder

extension Paths.Comments.WithCommentID.Properties {
    public func propertyID(_ propertyID: Int) -> WithPropertyID {
        WithPropertyID(path: "\(path)/\(propertyID)")
    }

    public struct WithPropertyID {
        /// Path: `/comments/{comment-id}/properties/{property-id}`
        public let path: String

        /// Get content property for comment by id
        ///
        /// Retrieves a specific Content Property by ID that is attached to a specified comment.
        /// 
        /// **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:
        /// Permission to view the comment.
        public var get: Request<ConfluenceKit.ContentProperty> {
            Request(path: path, method: "GET", id: "getCommentContentPropertiesById")
        }

        /// Update content property for comment by id
        ///
        /// Update a content property for a comment by its id. 
        /// 
        /// **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:
        /// Permission to edit the comment.
        public func put(_ body: ConfluenceKit.ContentPropertyUpdateRequest) -> Request<ConfluenceKit.ContentProperty> {
            Request(path: path, method: "PUT", body: body, id: "updateCommentPropertyById")
        }

        /// Delete content property for comment by id
        ///
        /// Deletes a content property for a comment by its id. 
        /// 
        /// **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:
        /// Permission to edit the comment.
        public var delete: Request<Void> {
            Request(path: path, method: "DELETE", id: "deleteCommentPropertyById")
        }
    }
}
