// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import HTTPHeaders
import URLQueryEncoder

extension Paths.Embeds.WithID {
    public var operations: Operations {
        Operations(path: path + "/operations")
    }

    public struct Operations {
        /// Path: `/embeds/{id}/operations`
        public let path: String

        /// Get permitted operations for a Smart Link in the content tree
        ///
        /// Returns the permitted operations on specific Smart Link in the content tree.
        /// 
        /// **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:
        /// Permission to view the Smart Link in the content tree and its corresponding space.
        public var get: Request<ConfluenceKit.PermittedOperationsResponse> {
            Request(path: path, method: "GET", id: "getSmartLinkOperations")
        }
    }
}
