// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import HTTPHeaders
import URLQueryEncoder

extension Paths.Blogposts.WithID {
    public var classificationLevel: ClassificationLevel {
        ClassificationLevel(path: path + "/classification-level")
    }

    public struct ClassificationLevel {
        /// Path: `/blogposts/{id}/classification-level`
        public let path: String

        /// Get blog post classification level
        ///
        /// Returns the [classification level](https://developer.atlassian.com/cloud/admin/dlp/rest/intro/#Classification%20level)
        /// for a specific blog post.
        /// 
        /// **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:
        /// 'Permission to access the Confluence site ('Can use' global permission) and permission to view the blog post.
        /// 'Permission to edit the blog post is required if trying to view classification level for a draft.
        public func get(status: Status? = nil) -> Request<ConfluenceKit.ClassificationLevel> {
            Request(path: path, method: "GET", query: makeGetQuery(status), id: "getBlogPostClassificationLevel")
        }

        private func makeGetQuery(_ status: Status?) -> [(String, String?)] {
            let encoder = URLQueryEncoder()
            encoder.encode(status, forKey: "status")
            return encoder.items
        }

        public enum Status: String, Codable, CaseIterable {
            case current
            case draft
            case archived
        }

        /// Update blog post classification level
        ///
        /// Updates the [classification level](https://developer.atlassian.com/cloud/admin/dlp/rest/intro/#Classification%20level)
        /// for a specific blog post.
        /// 
        /// **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:
        /// 'Permission to access the Confluence site ('Can use' global permission) and permission to edit the blog post.
        public func put(_ body: PutRequest) -> Request<Void> {
            Request(path: path, method: "PUT", body: body, id: "putBlogPostClassificationLevel")
        }

        public struct PutRequest: Encodable {
            /// The ID of the classification level.
            public var id: String
            /// Status of the content.
            public var status: Status

            /// Status of the content.
            public enum Status: String, Codable, CaseIterable {
                case current
                case draft
            }

            public init(id: String, status: Status) {
                self.id = id
                self.status = status
            }

            public func encode(to encoder: Encoder) throws {
                var values = encoder.container(keyedBy: StringCodingKey.self)
                try values.encode(id, forKey: "id")
                try values.encode(status, forKey: "status")
            }
        }
    }
}
