// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import HTTPHeaders
import URLQueryEncoder

extension Paths.Databases.WithID {
    public var operations: Operations {
        Operations(path: path + "/operations")
    }

    public struct Operations {
        /// Path: `/databases/{id}/operations`
        public let path: String

        /// Get permitted operations for a database
        ///
        /// Returns the permitted operations on specific database.
        /// 
        /// **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:
        /// Permission to view the database and its corresponding space.
        public var get: Request<ConfluenceKit.PermittedOperationsResponse> {
            Request(path: path, method: "GET", id: "getDatabaseOperations")
        }
    }
}
