// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import HTTPHeaders
import URLQueryEncoder

extension Paths {
    public static var databases: Databases {
        Databases(path: "/databases")
    }

    public struct Databases {
        /// Path: `/databases`
        public let path: String

        /// Create database
        ///
        /// Creates a database in the space.
        /// 
        /// **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:
        /// Permission to view the corresponding space. Permission to create a database in the space.
        public func post(isPrivate: Bool? = nil, _ body: PostRequest) -> Request<PostResponse> {
            Request(path: path, method: "POST", query: makePostQuery(isPrivate), body: body, id: "createDatabase")
        }

        public struct PostResponse: Decodable {
            /// ID of the database.
            public var id: String?
            /// The content type of the object.
            public var type: String?
            /// The status of the content.
            public var status: ConfluenceKit.ContentStatus?
            /// Title of the database.
            public var title: String?
            /// ID of the parent content, or null if there is no parent content.
            public var parentID: String?
            /// Content type of the parent, or null if there is no parent.
            public var parentType: ConfluenceKit.ParentContentType?
            /// Position of the database within the given parent page tree.
            public var position: Int32?
            /// The account ID of the user who created this database originally.
            public var authorID: String?
            /// The account ID of the user who owns this database.
            public var ownerID: String?
            /// Date and time when the database was created. In format "YYYY-MM-DDTHH:mm:ss.sssZ".
            public var createdAt: Date?
            public var version: ConfluenceKit.Version?
            public var links: ConfluenceKit.DatabaseLinks?

            public init(id: String? = nil, type: String? = nil, status: ConfluenceKit.ContentStatus? = nil, title: String? = nil, parentID: String? = nil, parentType: ConfluenceKit.ParentContentType? = nil, position: Int32? = nil, authorID: String? = nil, ownerID: String? = nil, createdAt: Date? = nil, version: ConfluenceKit.Version? = nil, links: ConfluenceKit.DatabaseLinks? = nil) {
                self.id = id
                self.type = type
                self.status = status
                self.title = title
                self.parentID = parentID
                self.parentType = parentType
                self.position = position
                self.authorID = authorID
                self.ownerID = ownerID
                self.createdAt = createdAt
                self.version = version
                self.links = links
            }

            public init(from decoder: Decoder) throws {
                let values = try decoder.container(keyedBy: StringCodingKey.self)
                self.id = try values.decodeIfPresent(String.self, forKey: "id")
                self.type = try values.decodeIfPresent(String.self, forKey: "type")
                self.status = try values.decodeIfPresent(ConfluenceKit.ContentStatus.self, forKey: "status")
                self.title = try values.decodeIfPresent(String.self, forKey: "title")
                self.parentID = try values.decodeIfPresent(String.self, forKey: "parentId")
                self.parentType = try values.decodeIfPresent(ConfluenceKit.ParentContentType.self, forKey: "parentType")
                self.position = try values.decodeIfPresent(Int32.self, forKey: "position")
                self.authorID = try values.decodeIfPresent(String.self, forKey: "authorId")
                self.ownerID = try values.decodeIfPresent(String.self, forKey: "ownerId")
                self.createdAt = try values.decodeIfPresent(Date.self, forKey: "createdAt")
                self.version = try values.decodeIfPresent(ConfluenceKit.Version.self, forKey: "version")
                self.links = try values.decodeIfPresent(ConfluenceKit.DatabaseLinks.self, forKey: "_links")
            }
        }

        private func makePostQuery(_ isPrivate: Bool?) -> [(String, String?)] {
            let encoder = URLQueryEncoder()
            encoder.encode(isPrivate, forKey: "private")
            return encoder.items
        }

        public struct PostRequest: Encodable {
            /// ID of the space.
            public var spaceID: String
            /// Title of the database.
            public var title: String?
            /// The parent content ID of the database.
            public var parentID: String?

            public init(spaceID: String, title: String? = nil, parentID: String? = nil) {
                self.spaceID = spaceID
                self.title = title
                self.parentID = parentID
            }

            public func encode(to encoder: Encoder) throws {
                var values = encoder.container(keyedBy: StringCodingKey.self)
                try values.encode(spaceID, forKey: "spaceId")
                try values.encodeIfPresent(title, forKey: "title")
                try values.encodeIfPresent(parentID, forKey: "parentId")
            }
        }
    }
}
